### ISSUE TITLE
where to get pretrain model? thanks you 

### ISSUE THREAD

**Issue by xiaoxiongmaoxuexi** [Lornatang/RFB_ESRGAN-PyTorch#1]

**Comment by Lornatang** [comment]
At present, we can't open source. We can use more than 25gb video memory for training.

**Comment by xiaoxiongmaoxuexi** [comment]
received it,thanks you from your answer. when it free to our people,i am looking forward to see result with your pretrain.&nbsp; thank thank you....




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Liu Changyu"<notifications@github.com&gt;; 
发送时间: 2020年10月23日(星期五) 下午4:05
收件人: "Lornatang/RFB_ESRGAN-PyTorch"<RFB_ESRGAN-PyTorch@noreply.github.com&gt;; 
抄送: "横推一切"<2430373246@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [Lornatang/RFB_ESRGAN-PyTorch] where to get pretrain model? thanks you  (#1)





 
At present, we can't open source. We can use more than 25gb video memory for training.

**Comment by xiaoxiongmaoxuexi** [comment]
i have a question asking for you ,if i want to train a model .what do i input? i try hr and lr as input, but it shows tensor question.hope you can answer this question to me,very thank you .


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Lornatang/RFB_ESRGAN-PyTorch"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月23日(星期五) 下午4:05
收件人:&nbsp;"Lornatang/RFB_ESRGAN-PyTorch"<RFB_ESRGAN-PyTorch@noreply.github.com&gt;;
抄送:&nbsp;"横推一切"<2430373246@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Lornatang/RFB_ESRGAN-PyTorch] where to get pretrain model? thanks you  (#1)





 
At present, we can't open source. We can use more than 25gb video memory for training.

**Comment by Lornatang** [comment]
Try to check the four shapes of NCHW

**Comment by xiaoxiongmaoxuexi** [comment]
thank for you.i try to it


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Lornatang/RFB_ESRGAN-PyTorch"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月26日(星期一) 上午8:46
收件人:&nbsp;"Lornatang/RFB_ESRGAN-PyTorch"<RFB_ESRGAN-PyTorch@noreply.github.com&gt;;
抄送:&nbsp;"横推一切"<2430373246@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Lornatang/RFB_ESRGAN-PyTorch] where to get pretrain model? thanks you  (#1)





 
Try to check the four shapes of NCHW

**Comment by xiaoxiongmaoxuexi** [comment]
i have a question,what it is your input.i want to refer from my picture. thank you. because i donot know how to change shapes of NCHW...thank from my heart.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Lornatang/RFB_ESRGAN-PyTorch"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月26日(星期一) 上午8:46
收件人:&nbsp;"Lornatang/RFB_ESRGAN-PyTorch"<RFB_ESRGAN-PyTorch@noreply.github.com&gt;;
抄送:&nbsp;"横推一切"<2430373246@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Lornatang/RFB_ESRGAN-PyTorch] where to get pretrain model? thanks you  (#1)





 
Try to check the four shapes of NCHW

**Comment by Lornatang** [comment]
The format accepted in pytorch is nchw format. Try toTensor() op.

**Comment by xiaoxiongmaoxuexi** [comment]
get it,thank for you.to be honest,no real to know how to op.i just want simplify to refer you from your input image.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Lornatang/RFB_ESRGAN-PyTorch"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月26日(星期一) 中午1:47
收件人:&nbsp;"Lornatang/RFB_ESRGAN-PyTorch"<RFB_ESRGAN-PyTorch@noreply.github.com&gt;;
抄送:&nbsp;"横推一切"<2430373246@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Lornatang/RFB_ESRGAN-PyTorch] where to get pretrain model? thanks you  (#1)





 
The format accepted in pytorch is nchw format. Try toTensor() op.

**Comment by Lornatang** [comment]
@xiaoxiongmaoxuexi I must close it now. I will reopen in next months.
