### ISSUE TITLE
无法使用DIV2K数据集进行训练

### ISSUE THREAD

**Issue by Jackson-LIMU** [Lornatang/RFB_ESRGAN-PyTorch#11]
按照教程准备好了DIV2K数据集的train和test，使用训练命令python train.py --arch rfb_esrgan data，但结果如下图：
![1628404883(1)](https://user-images.githubusercontent.com/75259876/128623378-77ff0bf0-598e-458f-8733-8fdfb397ebfc.png)
并没有训练的过程

**Comment by Lornatang** [comment]
目前已更新，数据集使用DIV8K。
