### ISSUE TITLE
generator部分的ReceptiveFieldBlock好像写错了

### ISSUE THREAD

**Issue by Jackson-LIMU** [Lornatang/RFB_ESRGAN-PyTorch#12]
![PYKW{ETBA_ I7_S73`6OW}7](https://user-images.githubusercontent.com/75259876/129003204-034001f0-8377-4acb-a8fa-62b47fe4da4d.png)
上图最后一步的输出应该是shortcut * scale_ratio吧？原论文的网络图如下：
![DY{BFZM8)Y2}BYRFYT0UO(9](https://user-images.githubusercontent.com/75259876/129003378-12f8f8a5-78d3-4cef-9442-aca2a0b20159.png)
可以看到是shortcut后面成了权重α

**Comment by Lornatang** [comment]
No~
