### ISSUE TITLE
plz tell me how to test my own images orz

### ISSUE THREAD

**Issue by Jamie1020** [Lornatang/RFB_ESRGAN-PyTorch#13]
simply modifying config.py seems to be useless

**Comment by Jamie1020** [comment]
sorry, i don't know how to test my own images.

**Comment by Lornatang** [comment]
Do you have files that generate a structure similar to the Set5 dataset?

**Comment by Jamie1020** [comment]
> Do you have files that generate a structure similar to the Set5 dataset?

yep，but i don't know which .py file should i run

**Comment by Lornatang** [comment]
modified config.py, run `python validate.py` 。T*^____^*
