### ISSUE TITLE
size error

### ISSUE THREAD

**Issue by wyuzyf** [Lornatang/RFB_ESRGAN-PyTorch#2]
UserWarning: Using a target size (torch.Size([1, 3, 1356, 204
0])) that is different to the input size (torch.Size([1, 3, 1224, 2040])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  
return F.l1_loss(input, target, reduction=self.reduction)

:  the generator net can be wrong?????

**Comment by Lornatang** [comment]
Please check all image size from directory?
Because I pass.
