### ISSUE TITLE
Missing requirements.txt & weight/RFB_ESRGAN_X4.pth

### ISSUE THREAD

**Issue by digit-jv** [Lornatang/RFB_ESRGAN-PyTorch#4]
The files requirements.txt & weight/RFB_ESRGAN_X4.pth are currently missing from the repo

**Comment by wyuzyf** [comment]
+1

**Comment by Lornatang** [comment]
@wyuzyf @digit-jv The requirement file has been updated. I will upload the trained weight file soon...

**Comment by kjerk** [comment]
Thanks for the updates!
