### ISSUE TITLE
Pretrained weights for RFB_ESRGAN

### ISSUE THREAD

**Issue by hyunjik11** [Lornatang/RFB_ESRGAN-PyTorch#7]
When are you planning to release the pretrained weights for `RFB_ESRGAN`?
I'm interested in the weights for the x16 model.
It would be great to have them so that I can try out the model on images.

**Comment by Lornatang** [comment]
@hyunjik11 I am currently discussing with relevant organizations whether to make the RFB_ESRGAN model public. Thank you for your support.

**Comment by hyunjik11** [comment]
Thanks for the quick reply.
Would you know where I can find publicly available pre-trained models that are competitive x16 super-resolution? e.g. ESRGAN or other baselines.
